name: build-and-deploy
on:
  push:
    branches: [ main ]        # roda sempre que você fizer push na main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: { node-version: 20 }
      - run: npm install
      - run: npm run build            # gera dist/main.js
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist          # publica só dist/ na branch gh-pages
